import EventComments from "@/components/EventComments";
import EventSlider from "@/components/EventDetails/EventSlider";
import RegisterBtn from "@/components/RegisterBtn";

import { Suspense } from "react";
export const metadata = {
    title: "event details || some",
    description: "Generated by create next app",
  };

const get_event_details = async (id) =>{
    try {
        const res = await fetch(`${process.env.NEXTAUTH_URL}/api/events/${id}`, {cache:"no-store"})
        const result =await  res.json();
        const data = await result.data;
        return data
    } catch (error) {
        
    }
}
const EventDetails = async ({params}) => {
        const data = await get_event_details(params.id);
        
    return (
        <div className="space-y-16">
            <div className="h-[40vh] grid place-items-center text-4xl font-extralight" style={{backgroundImage:'url(/images/slider.jpg)', backgroundRepeat:"no-repeat", backgroundSize:"cover" }}>
                        <h1 className="text-white p-2">{data.title} </h1>
            </div>
        <div className="container grid md:grid-cols-[60%_30%] grid-cols-1 justify-between">
                <section className=" space-y-6">
                        <EventSlider/>
                        <div className="mt-6">
                            <h2 className="text-2xl">	<span className=" font-bold">WHAT'S ABOUT EVENT /</span> <span className="font-thin">whats going on there come and learn</span></h2>
                        </div>
                        <div className="space-y-6">
                            <p>{data.details}</p>
                            <p>In hac habitasse platea dictumst. Curabitur eget dui id metus pulvinar suscipit. Quisque vitae ligula laoreet, scelerisque leo quis, facilisis metus. Sed pellentesque, urna sed varius consectetur, eros augue fringilla magna, id sem magna vel diam. Nulla sed hendrerit nunc.</p>
                        </div>

                      
                        <RegisterBtn className="text-white md:w-[300px] ">Register</RegisterBtn>


                        <div className="md:block hidden">
                        <Suspense fallback="Loading....">
                                {data.comments && <EventComments  commentsData={data.comments}/>}
                            </Suspense>
                        </div>


                </section>
                {/* <aside className="border md:p-4 mt-4">
                <Accordion type="multiple" collapsible ac="true">
                    <AccordionItem value="item-1">
                        <AccordionTrigger>When & Where</AccordionTrigger>
                        <AccordionContent >
                                <div>
                                    <h2>NYC - Financial Freedom Investor</h2>
                                    <p>Madison Ave</p>
                                    <p>{data.location}</p>
                                    <p>{format(new Date(data.dateInfo.date) , "mm-dd-yyyy")}</p>
                                    <p>{data.dateInfo.time}</p>

                                </div>
                        
                        </AccordionContent>
                    </AccordionItem>
                    <AccordionItem value="item-2">
                        <AccordionTrigger>Others</AccordionTrigger>
                        <AccordionContent>
                        Yes. It adheres to the WAI-ARIA design pattern.
                        </AccordionContent>
                    </AccordionItem>
                    </Accordion>
                </aside> */}

                <div className="md:hidden block">
                            
                            <Suspense fallback="Loading....">
                                {data.comments && <EventComments  commentsData={data.comments}/>}
                            </Suspense>
                        </div>
            
        </div>

        </div>
    );
};

export default EventDetails;